✨ 更新构建流程，添加对输出文件存在性的检查并创建 agent 目录及其主程序

diff --git a/.github/workflows/build-aio.yaml b/.github/workflows/build-aio.yaml
--- a/.github/workflows/build-aio.yaml
+++ b/.github/workflows/build-aio.yaml
@@ -197,9 +197,17 @@ jobs:
         if: matrix.goos == 'linux'
         run: |
           STD_ARCH="${{ matrix.goarch }}"
+          echo "OUTDIR=$OUTDIR"
+          echo "OUTNAME=$OUTNAME"
+          ls -lh $OUTDIR/
           if [[ "$STD_ARCH" =~ ^(amd64|arm64|arm|386|ppc64le|s390x)$ ]]; then
-            mkdir -p ${{ env.BIN_OUT }}/linux-$STD_ARCH
-            cp $OUTDIR/$OUTNAME ${{ env.BIN_OUT }}/linux-$STD_ARCH/spage
+            if [[ -f "$OUTDIR/$OUTNAME" ]]; then
+              mkdir -p ${{ env.BIN_OUT }}/linux-$STD_ARCH
+              cp "$OUTDIR/$OUTNAME" "${{ env.BIN_OUT }}/linux-$STD_ARCH/spage"
+            else
+              echo "File $OUTDIR/$OUTNAME not found!"
+              exit 1
+            fi
           fi
 
       - name: Upload artifact
